dog_odel/dog_odel/urls.py
from django.contrib import admin
from django.conf.urls import url, include, handler404,handler500
from django.urls import path
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

handler404 = 'dog_odel.views.handler404'
handler500 = 'dog_odel.views.handler500'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^about$', views.about, name='about'),
    url(r'^contact$', views.contact, name='contact'),
    url(r'^profilmembre$', views.profilmembre, name='profilmembre'),
    url(r'^dogo/', include('dogo.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

dog_odel/dogo/urls.py
from django.conf.urls import url
from . import views
from .models import *

app_name='dogo'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^index', views.index,name='index'),
	url(r'^subscribe', views.subscribe),
	url(r'^login', views.log),
	url(r'^logout', views.log_out),
    url(r'^(?P<obj>[A-Za-z]*)$', views.requete),
    url(r'^(?P<obj>[A-Za-z]*)/(?P<key>[0-9]*)$', views.show),
]

dog_odel/dogo/models.py
from django.db import models
from django.conf import settings


class SuperClass(models.Model):
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    @classmethod
    def all(self):
        return self.objects.all()

    @classmethod
    def find(self, key):
        try:
            return self.objects.filter(pk=key)
        except:
            raise Http404('Google who are you {} ?')

    def __str__(self):
        return self.nom

    class Meta:
        abstract = True


class Race(SuperClass):
    nom = models.CharField(max_length = 255)
    taille = models.IntegerField()
    morphologie = models.CharField(max_length = 255)
    comportement = models.CharField(max_length = 255)



class Proprietaire(SuperClass):
    nom = models.CharField(max_length=255)
    prenom = models.CharField(max_length=255, null=True)
    date_naissance = models.DateField()
    adresse = models.CharField(max_length=255)
    sexe = models.BooleanField()



class Chien(SuperClass):
    nom = models.CharField(max_length=255)
    date_naissance = models.DateField()
    couleur_poils = models.CharField(max_length=255)
    couleur_yeux = models.CharField(max_length=255)
    sexe = models.BooleanField()
    proprio = models.ForeignKey(Proprietaire,on_delete=models.CASCADE)
    race = models.ForeignKey(Race,on_delete=models.CASCADE)
    pere = models.ForeignKey('self', on_delete=models.CASCADE,null=True,blank=True,related_name='enfant_pere')
    mere = models.ForeignKey('self', on_delete=models.CASCADE,null=True,blank=True,related_name='enfant_mere')

dog_odel/dogo/forms.py
from .models import Photo
from django import forms

class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ('file', )

dog_odel/dog_odel/views.py
from django.shortcuts import render
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponseRedirect

def home(request):
    return render(request, 'pages/home.html')

def about(request):
    return render(request, 'pages/about.html')

def contact(request):
    return render(request, 'pages/contact.html')

def profilmembre(request):
    return render(request, 'pages/profilmembre.html')

def handler404(request):
    return render(request, 'errors/404.html', {}, status=404)

def handler500(request):
    return render(request, 'errors/500.html', {}, status=500)

def upload_file(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            handle_uploaded_file(request.FILES['file'])
            return HttpResponseRedirect('/success/url/')
    else:
        form = UploadFileForm()
    return render(request, 'upload.html', {'form': form})

dog_odel/dogo/views.py
from django.shortcuts import render,redirect
from .models import *
import sys
from django.contrib.auth import logout, get_user
from django.http import *
from django.contrib.auth.hashers import *
from datetime import datetime
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User
from django.contrib.auth import *


def index(request):
    objets = Chien.objects.order_by('created_at');
    return render(request, 'dogo/index.html', {'objets':objets})


def requete(request,obj):
    identifier = getattr(sys.modules[__name__], obj)
    objets = identifier.all()
    return render(request, 'dogo/requete.html', {'objets':objets})


def show(request, obj, key):
    identifier = getattr(sys.modules[__name__], obj)
    objet = identifier.find(int(key))
    return render(request, 'dogo/show.html', {'objet':objet})


def subscribe(request):
    mail = request.POST['mail']
    password = request.POST['password']
    nom = request.POST['name']
    prenom = request.POST['first_name']
    sexe = request.POST['sexe']
    date_naissance = request.POST['birth']

    User.objects.create_user(username=mail, email=mail, first_name=prenom, last_name=nom, password=password)

    return redirect('/dogo/index')


def log(request):
    username = request.POST['mail']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        login(request, user)
        return redirect('/dogo/index')
    else:
        return HttpResponse("Your username and password didn't match.")


def log_out(request):
    logout(request)
    return redirect('/dogo/index')

dog_odel/dogo/templates/dogo/formu.html
<form class="inscription_form" action="/dogo/subscribe/" method="post">
    <div class="modal fade" id="modal_inscription" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Inscription</h4>
                </div>
                <div class="modal-body">
                    {% csrf_token %}
                    <p><input type="email" name="mail" placeholder="E-mail" id="id_mail" required maxlength="100" /></p>
                    <p><input type="text" name="name" placeholder="Nom" id="id_name" required maxlength="100" /></p>
                    <p><input type="text" name="first_name" placeholder="Prenom" id="id_first_name" required maxlength="100" /></p>
                    <p><select name="sexe" data-placeholder="Sexe" id="id_sexe">
                        <option value="Male">Homme</option>
                        <option value="Femelle">Femme</option>
                    </select></p>
                    <p><input type="date" name="birth" placeholder="Année de naissance" id="id_birth" required /></p>
                    <p><input type="password" name="password" placeholder="Mot de passe" id="id_password" required /></p>
                    <input type="submit" value="Submit" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</form>

dog_odel/dogo/templates/dogo/gestionMembre.html
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang=fr>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/GestionMembre.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/section.css' %}" />

</head>
<body>
<button class="accordion">Ajouter un chien</button>
<div class="panel">
    <div class="form-style-3">
    {% csrf_token %}
        <form>
                <fieldset><legend>Ajout de Chien</legend>
                    <label for="field1"><span>Nom du Chien <span class="required">*</span></span><input type="text" class="input-field" name="nom" value="" /></label>
                    <label for="field2"><span>Date de Naissance <span class="required">*</span></span><input type="date" class="input-field" name="DateNais" value="" /></label>
                    <label for="field3"><span>Couleurs Poils <span class="required">*</span></span><input type="text" class="input-field" name="CouleursPo" value="" /></label>
                    <label for="field1"><span>Couleur des yeux <span class="required">*</span></span><input type="text" class="input-field" name="CouleursYe" value="" /></label>
                    <label for="field3"><span>Proprietaire<span class="required">*</span></span><input type="text" class="input-field" name="proprietaire" value="" /></label>
                    <label for="field4"><span>Race</span><select name="race" class="select-field"></label>
                    {% for objet in objets %}
                        <option value={{objet.id}}>{{object.race}}</option>
                    {% endfor %}
                    </select>
                    <label for="field4"><span>Père</span><select name="pere" class="select-field"></label>
                    {% for objet in objets %}
                        <option value={{objet.id}}>{{objet.nom}}</option>
                    {% endfor %}
                    </select>
                    <label for="field4"><span>Mère</span><select name="mere" class="select-field"></label>
                    {% for objet in objets %}
                        <option value={{objet.id}}>{{objet.nom}}</option>
                    {% endfor %}
                </select>
                    <label for="field4"><span>Sexe</span><select name="sexe" class="select-field">
                        <option value="F">F</option>
                        <option value="M">M</option>
                    </select></label>

            <div class="container">
                <img src="{% static 'img/chichi.jpg' %}" alt="Snow">
                <button class="btn">Button</button>
            </div>
        </form>
    </div>
</div>

<button class="accordion">Supprimer un chien</button>
<div class="panel">

</div>

<button class="accordion"></button>
<div class="panel">

</div>
{% endblock content %}
</body>
<script src="{% static 'js/GestionMembre.js' %}"></script>
</html>

dog_odel/dogo/templates/dogo/index.html
{% extends 'layouts/base.html' %}

{% block content %}

<h1> On a {{objets|length}} objets </h1>

<a href="{% url 'home' %}">Bon zonga ndaku, Rwandais !</a>
<a href="/doggybook/Chien">Liste des Chiens</a>
<a href="/doggybook/Proprietaire">Liste des Proprietaires</a>
<a href="{% url 'gestionMembre' %}"> Page de Gestion </a>
<a href="/doggybook/Race">Liste des Races</a>

{% endblock content %}

dog_odel/dogo/templates/dogo/login.html
<form class="connexion_form" action="/dogo/login/" method="post">
    <div class="modal fade" id="modal_connexion" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Connexion</h4>
                </div>
                <div class="modal-body">
                    {% csrf_token %}
                    <p><input type="email" name="mail" placeholder="E-mail" id="id_mail" required maxlength="100" /></p>
                    <p><input type="password" name="password" placeholder="Mot de passe" id="id_password" required /></p>
                    <input type="submit" value="Submit" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</form>

dog_odel/dogo/templates/dogo/profil.html
{% block content %}
{% load static %}

{% include 'layouts/head.html' %}

<body>

    {% include 'layouts/_navbar.html' %}

    <!-- Page Container -->
    <div class="w3-container w3-content" style="max-width:1400px;margin-top:80px">
        <!-- The Grid -->
        <div class="w3-row">
            <!-- Left Column -->
            <div class="w3-col m3">
                <!-- Profile -->
                <div class="w3-card w3-round w3-white">
                    <div class="w3-container">
                        <h4 class="w3-center">{{objet.first_name}}</h4>
                        <p class="w3-center"><img src="/w3images/avatar3.png" class="w3-circle" style="height:106px;width:106px" alt="Avatar"></p>
                        <hr>
                        <p><i class="fa fa-pencil fa-fw w3-margin-right w3-text-theme"></i> Designer, UI</p>
                        <p><i class="fa fa-home fa-fw w3-margin-right w3-text-theme"></i> London, UK</p>
                        <p><i class="fa fa-birthday-cake fa-fw w3-margin-right w3-text-theme"></i> April 1, 1988</p>
                    </div>
                </div>

            <!-- End Left Column -->
            </div>

            <!-- Middle Column -->
            <div class="w3-col m7">
                <div class="w3-row-padding">
                  <div class="w3-col m12">
                    <div class="w3-card w3-round w3-white">
                      <div class="w3-container w3-padding">
                        <h6 class="w3-opacity">Social Media template by w3.css</h6>
                        <p contenteditable="true" class="w3-border w3-padding">Status: Feeling Blue</p>
                        <button type="button" class="w3-button w3-theme"><i class="fa fa-pencil"></i> &nbsp;Post</button>
                      </div>
                    </div>
                  </div>
                </div>

                <div class="w3-container w3-card w3-white w3-round w3-margin"><br>
                    <img src="/w3images/avatar2.png" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:60px">
                    <span class="w3-right w3-opacity">1 min</span>
                    <h4>John Doe</h4><br>
                    <hr class="w3-clear">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>

                    <div class="w3-row-padding" style="margin:0 -16px">
                        <div class="w3-half">
                            <img src="/w3images/lights.jpg" style="width:100%" alt="Northern Lights" class="w3-margin-bottom">
                        </div>
                        <div class="w3-half">
                            <img src="/w3images/nature.jpg" style="width:100%" alt="Nature" class="w3-margin-bottom">
                        </div>
                    </div>
                    <button type="button" class="w3-button w3-theme-d1 w3-margin-bottom"><i class="fa fa-thumbs-up"></i> &nbsp;Like</button>
                    <button type="button" class="w3-button w3-theme-d2 w3-margin-bottom"><i class="fa fa-comment"></i> &nbsp;Comment</button>
                </div>

                <div class="w3-container w3-card w3-white w3-round w3-margin"><br>
                    <img src="/w3images/avatar5.png" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:60px">
                    <span class="w3-right w3-opacity">16 min</span>
                    <h4>Jane Doe</h4><br>
                    <hr class="w3-clear">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                    <button type="button" class="w3-button w3-theme-d1 w3-margin-bottom"><i class="fa fa-thumbs-up"></i> &nbsp;Like</button>
                    <button type="button" class="w3-button w3-theme-d2 w3-margin-bottom"><i class="fa fa-comment"></i> &nbsp;Comment</button>
                </div>

                <div class="w3-container w3-card w3-white w3-round w3-margin"><br>
                    <img src="/w3images/avatar6.png" alt="Avatar" class="w3-left w3-circle w3-margin-right" style="width:60px">
                    <span class="w3-right w3-opacity">32 min</span>
                    <h4>Angie Jane</h4><br>
                    <hr class="w3-clear">
                    <p>Have you seen this?</p>
                    <img src="/w3images/nature.jpg" style="width:100%" class="w3-margin-bottom">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                    <button type="button" class="w3-button w3-theme-d1 w3-margin-bottom"><i class="fa fa-thumbs-up"></i> &nbsp;Like</button>
                    <button type="button" class="w3-button w3-theme-d2 w3-margin-bottom"><i class="fa fa-comment"></i> &nbsp;Comment</button>
                </div>

            <!-- End Middle Column -->
            </div>
        </div>
    </div>

    {% include 'layouts/script.html' %}

    {% endblock content %}
    {% include 'layouts/footer.html' %}

</body>
</html>

dog_odel/dogo/templates/dogo/requete.html
{% extends 'layouts/base.html' %}

{% block content %}

<h1> On a {{objets|length}} objets </h1>

<h7>
  <pre>
    {% for objet in objets %}
      <h1> {{objet.id}}. {{objet.nom|upper}} {{objet.couleur_yeux|truncatewords:2}}</h1>
    {% endfor %}
  </pre>
</h7>

<a href="{% url 'home' %}">Bon zonga ndaku, Rwandais !</a>

{% endblock content %}

dog_odel/dogo/templates/dogo/show.html
{% extends 'layouts/base.html' %}

{% block content %}

{% for obj in objet %}
<h1>Objet {{obj.id}} detail</h1>
<h2>{{obj.nom}}</h2>
{% endfor %}

<p> <a href="{% url 'DoggyBook:index' %}">Accueil</a> </p>

{% endblock content %}

dog_odel/dogo/templates/dogo/subscribe.html
<form class="inscription_form" action="/doggybook/subscribe/" method="post">
    <div class="modal fade" id="modal_inscription" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Inscription</h4>
                </div>
                <div class="modal-body">
                    {% csrf_token %}
                    <p><input type="email" name="mail" placeholder="E-mail" id="id_mail" required maxlength="100" /></p>
                    <p><input type="text" name="name" placeholder="Nom" id="id_name" required maxlength="100" /></p>
                    <p><input type="text" name="first_name" placeholder="Prenom" id="id_first_name" required maxlength="100" /></p>
                    <p><select name="sexe" data-placeholder="Sexe" id="id_sexe">
                        <option value="Male">Homme</option>
                        <option value="Femelle">Femme</option>
                    </select></p>
                    <p><input type="date" name="birth" placeholder="Année de naissance" id="id_birth" required /></p>
                    <p><input type="password" name="password" placeholder="Mot de passe" id="id_password" required /></p>
                    <input type="submit" value="Submit" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</form>

dog_odel/templates/layouts/_navbar.html
{% load static %}
{% block content %}
<!-- Navbar (sit on top) -->
<div class="w3-top">
  <div class="w3-bar w3-white w3-card" id="myNavbar">
    <a href="{% url 'home' %}" class="w3-bar-item w3-button"><img src="{% static 'img/dogo3.png' %}" alt="Accueil" title="Accueil" width="27px"/><b>  DoggyBook</b></a>
    <!-- Right-sided navbar links -->
    {% if request.user.is_authenticated %}
    <!-- Right-sided navbar links -->
    <div class="w3-right w3-hide-small">
      <a href="{% url 'about' %}" class="w3-bar-item w3-button"><i class="fa fa-usd"></i> ABOUT</a>
      <a href="{% url 'contact' %}" class="w3-bar-item w3-button"><i class="fa fa-envelope"></i> TEAM</a>
      <a data-toggle="modal" href="{% url 'profilmembre' %}" class="w3-bar-item w3-button"><i class="fa fa-user"></i> {{user.first_name.upper}}</a>
      <a data-toggle="modal" href="/dogo/logout" class="w3-bar-item w3-button"><i class="fa fa-usd"></i> DECONNEXION</a>
      <a href="#" class="w3-bar-item w3-button w3-right w3-hover-red w3-text-grey"><i class="fa fa-search"></i></a>
    </div>
    {% else %}
    <div class="w3-right w3-hide-small">
      <a href="{% url 'about' %}" class="w3-bar-item w3-button"><i class="fa fa-usd"></i> ABOUT</a>
      <a href="{% url 'contact' %}" class="w3-bar-item w3-button"><i class="fa fa-envelope"></i> TEAM</a>
      <a data-toggle="modal" href="dogo/formu views.formu #modal_inscription" class="w3-bar-item w3-button"><i class="fa fa-user"></i> INSCRIPTION</a>
      <a data-toggle="modal" href="dogo/login views.formu_submit #modal_connexion" class="w3-bar-item w3-button"><i class="fa fa-usd"></i> CONNEXION</a>
      <a href="#" class="w3-bar-item w3-button w3-right w3-hover-red w3-text-grey"><i class="fa fa-search"></i></a>
    </div>
    {% endif %}
    <a href="javascript:void(0)" class="w3-bar-item w3-button w3-right w3-hide-large w3-hide-medium" onclick="w3_open()"><i class="fa fa-bars"></i></a>
    <a data-toggle="modal" href="javascript:void(0); {% url 'profilmembre' %}" class="w3-bar-item w3-button w3-right w3-hide-large w3-hide-medium"><i class="fa fa-user"></i> {{user.first_name}}</a>
    <!-- Overlay effect when opening sidebar on small screens -->
    <div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>
  </div>
</div>

<!-- Sidebar on small screens when clicking the menu icon -->
<nav class="w3-sidebar w3-bar-block w3-black w3-card w3-animate-left w3-hide-medium w3-hide-large" style="display:none" id="mySidebar">
  {% if request.user.is_authenticated %}
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-bar-item w3-button w3-large w3-padding-16">Close ×</a>
  <a href="{% url 'about' %}" onclick="w3_close()" class="w3-bar-item w3-button"> ABOUT</a>
  <a href="{% url 'contact' %}" onclick="w3_close()" class="w3-bar-item w3-button"> TEAM</a>
  <a data-toggle="modal" href="{% url 'profilmembre' %}" onclick="w3_close()" class="w3-bar-item w3-button"> {{user.first_name.upper}}</a>
  <a data-toggle="modal" href="/dogo/logout" onclick="w3_close()" class="w3-bar-item w3-button"> DECONNEXION</a>
  {% else %}
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-bar-item w3-button w3-large w3-padding-16">Close ×</a>
  <a href="{% url 'about' %}" onclick="w3_close()" class="w3-bar-item w3-button"> ABOUT</a>
  <a href="{% url 'contact' %}" onclick="w3_close()" class="w3-bar-item w3-button"> TEAM</a>
  <a data-toggle="modal" href="dogo/formu views.formu #modal_inscription" onclick="w3_close()" class="w3-bar-item w3-button"> INSCRIPTION</a>
  <a data-toggle="modal" href="dogo/login views.formu_submit #modal_connexion" onclick="w3_close()" class="w3-bar-item w3-button"> CONNEXION</a>
  {% endif %}
</nav>



    {% include 'dogo/login.html' %}
    {% include 'dogo/formu.html' %}
{% endblock content %}

dog_odel/templates/layouts/base.html
{% include 'layouts/head.html' %}
<body>

    {% include 'layouts/_navbar.html' %}
    {% block content %}{% endblock content %}
    {% include 'layouts/footer.html' %}

</body>

</html>

dog_odel/templates/layouts/footer.html
{% block content %}
</div>
<footer>
    <nav class="navbar navbar-default navbar-bottom">
        <div class="container-fluid">
            <ul class="nav navbar-nav navbar-left">
                <li> <a href="https://sciences.edu.umontpellier.fr" title="W3.CSS" target="_blank">FDS UM2</a>Copyright &copy;2018</li>
            </ul>
            <ul class="nav navbar-nav navbar-right">

            </ul>
        </div>
    </nav>
</footer>
<script>
var myIndex = 0;
carousel();

function carousel() {
    var i;
    var x = document.getElementsByClassName("mySlides");
    for (i = 0; i < x.length; i++) {
       x[i].style.display = "none";
    }
    myIndex++;
    if (myIndex > x.length) {myIndex = 1}
    x[myIndex-1].style.display = "block";
    setTimeout(carousel, 4000);
}
var mySidebar = document.getElementById("mySidebar");
function w3_open() {
    if (mySidebar.style.display === 'block' & myOverlay.style.display === 'block') {
      myOverlay.style.display = 'none';
      mySidebar.style.display = 'none';
    } else {
        mySidebar.style.display = 'block';
        myOverlay.style.display = "block";
    }
}
// Close the sidebar with the close button
function w3_close() {
    mySidebar.style.display = "none";
    myOverlay.style.display = "none";
}
</script>

{% endblock content %}

dog_odel/templates/layouts/head.html
<!DOCTYPE html>
<html lang=fr>
<head>
    <meta charset="utf-8">
    <title>DoggyBook</title>
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/svg" href="{% static 'img/dogo3.svg' %}" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- Custom Theme files -->
    <!-- <link href="css/style.css" rel="stylesheet" type="text/css" media="all" /> -->
    <!-- //Custom Theme files -->
    <!-- web font -->
    <link href="//fonts.googleapis.com/css?family=Poiret+One&amp;subset=cyrillic,latin-ext" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Josefin+Sans:100,100i,300,300i,400,400i,600,600i,700,700i&amp;subset=latin-ext" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>

dog_odel/templates/pages/home.html
{% extends 'layouts/base.html' %}

    {% block content %}
    <!-- {% include 'layouts/header.html' %} -->
    <a href="{% url 'dogo:index' %}">Bon appétit cousin</a>
    {% endblock %}

dog_odel/templates/pages/profilmembre.html
{% block content %}
{% load static %}

{% include 'layouts/head.html' %}

<body>

    {% include 'layouts/_navbar.html' %}

    <!-- {% include 'layouts/header.html' %} -->



    {% include 'layouts/footer.html' %}

</body>

{% endblock content %}